# -*- coding: utf-8 -*-
"""Task_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J6WwVfEuTLCGzAxTZ-tP46y3BSfBourx
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset (replace 'laptop_sales.csv' with your file path)
laptop_sales_data = pd.read_csv("/content/task_02_ds.csv")

# Assuming the brand information is in a column named 'Brand'
# Count the occurrences of each brand
brand_counts = laptop_sales_data['Brand'].value_counts()

# Plot the distribution of brands using a bar chart
plt.figure(figsize=(10, 6))
brand_counts.plot(kind='bar', color='skyblue')
plt.title('Distribution of Laptop Brands')
plt.xlabel('Brand')
plt.ylabel('Number of Sales')
plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset (replace 'laptop_sales.csv' with your file path)
laptop_sales_data = pd.read_csv("/content/task_02_ds.csv")

# Plot the box plot
plt.figure(figsize=(12, 8))
sns.boxplot(x='Brand', y='Price', data=laptop_sales_data, palette='Set3')
plt.title('Distribution of Price by Brand')
plt.xlabel('Brand')
plt.ylabel('Price')
plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.tight_layout()
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset (replace 'laptop_sales.csv' with your file path)
laptop_sales_data = pd.read_csv("/content/task_02_ds.csv")

# Assuming we want to visualize the correlation between numerical variables
# Select numerical columns for the heatmap
numerical_cols = laptop_sales_data.select_dtypes(include='number')

# Compute the correlation matrix
correlation_matrix = numerical_cols.corr()

# Create the heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap of Laptop Sales Dataset')
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

# Load the dataset (replace 'laptop_sales.csv' with your file path)
laptop_sales_data = pd.read_csv("task_02_ds.csv")

# Encode the 'Processor' column as numerical using label encoding
processor_encoder = LabelEncoder()
laptop_sales_data['Processor'] = processor_encoder.fit_transform(laptop_sales_data['Processor'])

# Filter out any missing values in 'Processor' and 'Brand' columns
processor_brand_data = laptop_sales_data[['Processor', 'Brand']].dropna()

# Plot scatter plot
plt.figure(figsize=(10, 6))
sns.scatterplot(x='Processor', y='Brand', data=processor_brand_data)
plt.title('Scatter Plot of Processor by Brand')
plt.xlabel('Processor')
plt.ylabel('Brand')
plt.xticks(rotation=45)  # Rotate x-axis labels for better readability
plt.tight_layout()
plt.show()